name: Build and Deploy Asset Builder

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Asset Builder
        run: |
          cd BUILD-ASSETS-PROJECT
          docker build -t ${{ secrets.DOCKER_USERNAME }}/build-assets-project-asset-builder:latest .

      - name: Push Docker image for Asset Builder
        run: docker push ${{ secrets.DOCKER_USERNAME }}/build-assets-project-asset-builder:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/build-assets-project-asset-builder:latest
            cd /path/to/your/docker-compose
            docker-compose pull
            docker-compose up -d
          EOF
