name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ghcr.io/your-repo/asset-builder:latest .

      - name: Push Docker image
        run: docker push ghcr.io/your-repo/asset-builder:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/your-repo/asset-builder:latest
            docker-compose down
            docker-compose up -d

