version: '3.8'

services:
  wordpress:
    image: habeeb24/wordpress:latest
    container_name: wordpress
    ports:
      - "9590:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress-db

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress-db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
