version: '3.8'

services:
  wordpress:
    image: habeeb24/wordpress:latest  # Your Docker Hub image
    container_name: wordpress
    ports:
      - "9595:80"  # Adjust the port mapping as needed
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

    env:
      WORDPRESS_DB_HOST: ${{ secrets.DB_HOST }}
      WORDPRESS_DB_NAME: ${{ secrets.DB_NAME }}
      WORDPRESS_DB_USER: ${{ secrets.DB_USER }}
      WORDPRESS_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

