version: '3.8'

services:
  wordpress:
    image: habeeb24/wordpress:latest
    container_name: wordpress
    ports:
      - "9590:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password  # This should match MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: wordpress-db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password   # Set the root password here
      MYSQL_DATABASE: wordpress-db    # Optional: create a database on startup
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
