version: '3.8'

services:
  wordpress:
    image: habeeb24/wordpress:latest  # Your Docker Hub image
    container_name: wordpress
    ports:
      - "9595:80"  # Adjust the port mapping as needed
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress-db


  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

