name: Deploy WordPress to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Navigate to Build Assets Project
        working-directory: ./BUILD-ASSETS-PROJECT
        run: |
          echo "Current directory contents:"
          ls -al
          echo "Installing dependencies..."
          npm install
          echo "Building assets..."
          npm run build

      - name: Build Docker image
        working-directory: ./BUILD-ASSETS-PROJECT
        run: |
          echo "Current directory contents in Docker build context:"
          ls -al
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            # Check Docker service status
            sudo systemctl status docker

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:latest

            # Navigate to the directory containing docker-compose.yml
            cd /home/ubuntu/docker

            # Stop and remove existing containers
            docker-compose down

            # Pull the latest images and recreate containers
            docker-compose pull
            docker-compose up -d
          EOF
