name: Pull, Push, and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  pull-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Push Docker Images
        run: |
          docker pull wordpress:latest
          docker tag wordpress:latest ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
          docker pull mysql:5.7
          docker tag mysql:5.7 ${{ secrets.DOCKER_USERNAME }}/mysql:5.7
          docker push ${{ secrets.DOCKER_USERNAME }}/mysql:5.7

      - name: Test DNS Resolution
        run: |
          nslookup ${{ secrets.EC2_HOST }}
          ping -c 4 ${{ secrets.EC2_HOST }}

      - name: Deploy to EC2 with Docker Compose
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          ls -la ~/.ssh
          cat ~/.ssh/known_hosts
          ssh-keygen -y -f ~/.ssh/id_rsa

          # Ensure Docker and Docker Compose are installed and running
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$EC2_HOST << 'EOF'
            sudo systemctl restart docker
            cd /actual/path/to/your/docker-compose-directory
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker-compose ps
          EOF
