name: Deploy WordPress to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          
          # Create the SSH key file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Add the host to known_hosts to prevent host key verification issues
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          
          # SSH into the EC2 instance and execute commands
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv ubuntu@$EC2_HOST << 'EOF'
            # Ensure Docker is installed and running
            sudo systemctl status docker || sudo systemctl start docker

            # Pull the latest WordPress and MySQL images from Docker Hub
            sudo docker pull wordpress:latest
            sudo docker pull mysql:5.7

            # Stop and remove any existing WordPress and MySQL containers
            sudo docker stop wordpress-container mysql-container || true
            sudo docker rm wordpress-container mysql-container || true

            # Run the WordPress container
            sudo docker run -d --name wordpress-container \
              -p 80:80 \
              -e WORDPRESS_DB_HOST=mysql-container:3306 \
              -e WORDPRESS_DB_USER=exampleuser \
              -e WORDPRESS_DB_PASSWORD=examplepass \
              -e WORDPRESS_DB_NAME=exampledb \
              wordpress:latest

            # Run the MySQL container
            sudo docker run -d --name mysql-container \
              -e MYSQL_ROOT_PASSWORD=examplepass \
              -e MYSQL_DATABASE=exampledb \
              -e MYSQL_USER=exampleuser \
              -e MYSQL_PASSWORD=examplepass \
              mysql:5.7

            # Optional: Check the status of the containers
            sudo docker ps
          EOF
